apiVersion: v1
kind: Service
metadata:
  name: gitops-workshop
  namespace: workshop-gitops
  labels:
    app: gitops-workshop
spec:
  selector:
    app: gitops-workshop
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
