apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: gitops-workshop
  labels:
    app: gitops-workshop
spec:
  to:
    kind: Service
    name: gitops-workshop
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
